### ISSUE TITLE
Failed to load config!

### ISSUE THREAD

**Issue by Thebomb32** [VoltCruelerz/Greed#14]
System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\Config.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Greed.Utils.Settings.LoadConfig() in C:\Users\VoltC\AppData\Local\sins2\Greed\Greed\Utils\Settings.cs:line 38

**Comment by Thebomb32** [comment]
I replaced my name with the capital X you see in the file location. I don't think it will matter though. Thanks

[2023/12/03 | 07:17:14.785] [INFO] - Migrated to C:\Users\X\AppData\Local\sins2\mods
[2023/12/03 | 07:17:14.789] [INFO] =================================
- Migrating Down Dir...
- - JSON: 
- - XML: 
- - Default: C:\Users\X\Downloads
[2023/12/03 | 07:17:14.790] [INFO] Migrating from dll.config...
[2023/12/03 | 07:17:14.790] [INFO] =================================
- Migrating Sins Dir...
- - JSON: 
- - XML: 
- - Default: C:\Program Files\Epic Games\SinsII
[2023/12/03 | 07:17:14.790] [INFO] - Migrated to C:\Program Files\Epic Games\SinsII
[2023/12/03 | 07:17:14.792] [INFO] =================================
- Migrating Channel...
- - JSON: live
- - XML: 
- - Default: live
[2023/12/03 | 07:17:14.792] [INFO] - Migrated to live
[2023/12/03 | 07:17:14.793] [INFO] =================================
- Migrating Export Dir...
- - JSON: 
- - XML: 
- - Default: C:\Users\X\AppData\Local\sins2\mods
[2023/12/03 | 07:17:14.794] [INFO] =================================
- Migrating Mods Dir...
- - JSON: 
- - XML: 
- - Default: C:\Users\X\AppData\Local\sins2\mods
[2023/12/03 | 07:17:14.794] [INFO] - Migrated to C:\Users\X\AppData\Local\sins2\mods
[2023/12/03 | 07:17:14.795] [INFO] - Migrated to C:\Users\X\Downloads
[2023/12/03 | 07:17:14.795] [INFO] Tabs_SelectionChanged()
[2023/12/03 | 07:17:14.795] [INFO] Mod Dir: C:\Users\X\AppData\Local\sins2\mods
[2023/12/03 | 07:17:14.796] [INFO] Sins II Dir: C:\Program Files\Epic Games\SinsII
[2023/12/03 | 07:17:14.797] [INFO] Components Loaded
[2023/12/03 | 07:17:14.797] [ERROR] Failed to load config!
System.IO.FileNotFoundException: Could not find file 'C:\Users\X\Desktop\Config.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Greed.Utils.Settings.LoadConfig()
[2023/12/03 | 07:17:14.967] [INFO] Refreshing mod list UI for 0 mods...
[2023/12/03 | 07:17:14.967] [INFO] Mod Dir: C:\Users\X\AppData\Local\sins2\mods
[2023/12/03 | 07:17:14.968] [INFO] Sins II Dir: C:\Program Files\Epic Games\SinsII
